#pragma once
#include <huw.hpp>



#define GRAVITY 325

#define RESX 1280
#define RESY 704
#define PLAYER_SIZE 64


#define ACCELERATION_DURATION_HORIZONTAL 1.0
#define ACCELERATION_DURATION_VERTICAL 1.0
//HASE MOVESET
#define HASE_ACCELERATION_HORIZONTAL 120
#define HASE_DECELERATION_HORIZONTAL 120

#define HASE_ACCELERATION_VERTICAL 400
#define HASE_DECELERATION_VERTICAL 0

//WOLF MOVESET
#define WOLF_ACCELERATION_HORIZONTAL 60
#define WOLF_DECELERATION_HORIZONTAL 60

#define WOLF_ACCELERATION_VERTICAL 170
#define WOLF_DECELERATION_VERTICAL 0


//GEGNER
#define TAUBE_SPEED 30