#include <huw.hpp>

#define GRAVITY 50

#define RESX 1280
#define RESY 720
#define PLAYER_SIZE 64


#define ACCELERATION_DURATION_HORIZONTAL 1.0
//HASE MOVESET
#define HASE_ACCELERATION_HORIZONTAL 120
#define HASE_DECELERATION_HORIZONTAL 120

//WOLF MOVESET
#define WOLF_ACCELERATION_HORIZONTAL 60
#define WOLF_DECELERATION_HORIZONTAL 60

